# Site settings
title: "x3rz blog"
bye_message: "Bye!!"
baseurl: "/clyell/"
url: "https://x3rz.github.io"
disqus: x3rz

# Header settings
nick: "x3rz"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "x3rz"
#blog:
 #   server: "wordpress.com"
 #   nick: "gjuniioor"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
